### ISSUE TITLE
FE - Podmiana ikon na własne w formacie svg

### ISSUE THREAD

**Issue by Tomasz-Budny** [SGGW-Projekt-Zespolowy/SocialNetworkService-FE#17]
W tym celu najlepiej użyć package'u: angular-svg-icon, na spotkaniu wytłumaczę Ci jak to dokładnie działa.

Konieczna będzie podmiana wszystkich dotychczasowych ikon, dodanych z fontawesome, na nasze osobiste - wyeksportowane przez Agatę w formacie svg. Konieczne może być również dostosowanie styli do nowych ikon.
Na końcu usuwamy odniesienie do fontawesome z index.html

**Comment by JWierzbix** [comment]
approved 3 points
