### ISSUE TITLE
FE Stworzenie dropdown menu dla wyboru tytułu naukowego

### ISSUE THREAD

**Issue by Tomasz-Budny** [SGGW-Projekt-Zespolowy/SocialNetworkService-FE#7]
Obecnie wygląda ono tak:

![image](https://user-images.githubusercontent.com/76007156/235297621-90f7f1a9-bff1-47fa-b749-079100be5633.png)

Należy przestylować to tak aby odpowiadało projektowi na Figma. W miarę możliwości nie korzystać z bootstrapa ani innych sccsowych bibliotek (żadna nie jest nawet zainstalowana).

**Comment by JWierzbix** [comment]
approved 3 points
